global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  # Add alerting rules here if needed

scrape_configs:
  # Node Exporter for system metrics (CPU, memory, disk, network)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s
    metrics_path: /metrics

  # Netdata for detailed system monitoring
  - job_name: 'netdata'
    metrics_path: '/api/v1/allmetrics'
    params:
      format: ['prometheus']
    static_configs:
      - targets: ['netdata:19999']
    scrape_interval: 5s

  # Docker container metrics (if docker daemon exposes metrics)
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 10s
    metrics_path: /metrics

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s

  # Keycloak metrics (if enabled via management interface)
  - job_name: 'keycloak'
    static_configs:
      - targets: ['keycloak:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    # Note: Keycloak needs to be configured to expose metrics
    # This may require additional configuration in Keycloak

  # Container monitoring via cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 5s
    metrics_path: /metrics
