global:
  scrape_interval: 2s  # High frequency for performance testing
  evaluation_interval: 2s

rule_files:
  # Add alerting rules here if needed

scrape_configs:
    
  # Keycloak Built-in Metrics (management interface)
  - job_name: 'keycloak-builtin'
    static_configs:
      - targets: ['keycloak:9000']
    scrape_interval: 2s
    metrics_path: '/metrics'
    
  # Container metrics focused on Keycloak container only
  - job_name: 'keycloak-container'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 2s
    metrics_path: /metrics
    
  # Essential system metrics for performance correlation
  - job_name: 'system-cpu-memory'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 2s
    metrics_path: /metrics


